image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080

vscode:
  extensions:
    - golang.go
    - streetsidesoftware.code-spell-checker
    - coenraads.bracket-pair-colorizer-2
    - oderwat.indent-rainbow
